### ISSUE TITLE
Widget | Zabbix

### ISSUE THREAD

**Issue by szymon-owczarzak** [Cognifide/cogboard#233]
### Short Description
We need additional Widget for presenting information from Zabbix. This new widget is able to show information about: cpu, ram, heap, disk, disk (specific directory), logged users, maybe more?

#### Solution (optional)
Widget should present information based on its configuration.

More details about solution can be found in original JIRA ticket **CLAN6-130** and **CLAN6-181**

### Acceptance Criteria
 - [x] New widget called Zabbix is available
 - [x] Admin can configure: schedule period, endpoint, metrics
 - [x] Each metric have a range field for warning message (see examples below)
 - [x] User can see configured metrics on widget
 - [ ] Automated tests added

#### Examples
CPU rage is set to 50-80 | <=50 ok (green) | >50 <=80 warning (yellow) | >80 error (red)
CPU rage is set to 100-100 | always (green)
CPU rage is set to 50-50 | <=50 ok (green) | >50  error (red)

**Comment by basia-wulnikowska** [comment]
Automated tests will be written later - together with rewriting old tests
