### ISSUE TITLE
Unable to configure endpoint containing port number

### ISSUE THREAD

**Issue by szymon-owczarzak** [Cognifide/cogboard#234]
**Describe the bug**
Fix for URL and Public URL input that does not support endpoints with port number.

**Expected behavior**
Admin is unable to configure endpoint containing port number.
"Invalid URL" error message is shown.

**Expected behavior**
Admin is able to configure endpoint containing port number.

 - [ ] Admin can set any URL from below examples
 - [ ] Automated tests added / updated

### Examples:

- https//123.123.123.13:9082
- https//comanin.com:9082
- https//comanin.com

**Comment by mpiotrowski1** [comment]
Automated Cypress test added.

Tested & accepted.
