### ISSUE TITLE
Option to clear endpoint and credential

### ISSUE THREAD

**Issue by szymon-owczarzak** [Cognifide/cogboard#235]
**Describe the bug**
Sometimes we have endpoint which don't need any credentials (I want to have possibility to choose empty row in credentials select field).

Same situation with endpoints (we need to check were we can use that - eg in service check i can add absolute path and don't use endpoint).

## Acceptance Criteria
 - [x] Admin can select empty endpoint for Service Check Widget 
 - [x] Admin can select empty credential for any endpoint
 - [x] Automated tests updated
 - [ ] Update WIKI if needed.

**Comment by mpiotrowski1** [comment]
Tested & accepted.
