### ISSUE TITLE
Config not recteated after delete

### ISSUE THREAD

**Issue by szymon-owczarzak** [Cognifide/cogboard#236]
**Describe the bug**
If `/mnt/config.json` is removed when app is running then after refresh app is no longer working.
When `config.json` is missing it is created on demand on startup - this should be done each time when config is missing.

**To Reproduce**
1. Remove config.json on running app
2. Refresh page
3. App does not work

**Expected behavior**
App is still working

**Workaround**
Restart APP

 ### Solution proposition
Fix: refactor VolumeStorageFactory to singleton - use it in services so it will use:
`createIfDoesNotExist(path)` method each time any storage is loaded.

**Comment by mpiotrowski1** [comment]
Tested & accepted.
