### ISSUE TITLE
Support for proxy configuration might be needed

### ISSUE THREAD

**Issue by SebaM** [Cognifide/cogboard#250]
### Short Description
Team

I tried to install it locally on my env. However, I'm after firewall thus I would need to configure proxy server to be able to fetch any artefacts from the internet. Thus I called gradle as:
./gradlew -Dhttp.proxyHost=135.245.X.X -Dhttp.proxyPort=8000 -Dhttps.proxyHost=135.245.X.X -Dhttps.proxyPort=8000 --debug

unfortunately, it didn't help my installation failed as below:
17:40:40.860 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 536870912, Committed: 401604608}
16:22:59.452 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger]
16:22:59.452 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :cogboard-webapp:npmInstall
17:40:41.163 [ERROR] [system.err] npm ERR! code ECONNRESET
17:40:41.166 [ERROR] [system.err] npm ERR! errno ECONNRESET
17:40:41.169 [ERROR] [system.err] npm ERR! network request to https://registry.npmjs.org/react-iframe failed, reason: read ECONNRESET
17:40:41.171 [ERROR] [system.err] npm ERR! network This is a problem related to network connectivity.
17:40:41.178 [ERROR] [system.err] npm ERR! network In most cases you are behind a proxy or have bad network settings.
17:40:41.178 [ERROR] [system.err] npm ERR! network
17:40:41.178 [ERROR] [system.err] npm ERR! network If you are behind a proxy, please make sure that the
17:40:41.178 [ERROR] [system.err] npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
17:40:41.247 [ERROR] [system.err]
17:40:41.247 [ERROR] [system.err] npm ERR! A complete log of this run can be found in:
17:40:41.248 [ERROR] [system.err] npm ERR!     /home/malyska/.npm/_logs/2020-02-11T16_40_41_198Z-debug.log
17:40:41.257 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
17:40:41.258 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/home/malyska/dev/cogboard/cogboard-webapp/.gradle/nodejs/node-v10.16.0-linux-x64/bin/npm'' finished with exit value 1 (state: FAILED)
17:40:41.260 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute exec for :cogboard-webapp:npmInstall'
17:40:41.260 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute exec for :cogboard-webapp:npmInstall' completed
17:40:41.261 [DEBUG] [org.gradle.api.internal.tasks.execution.DefaultTaskSnapshotter] Snapshotting property $1 (Output) for task ':cogboard-webapp:npmInstall'
17:40:41.265 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Removed task artifact state for {} from context.
17:40:41.265 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :cogboard-webapp:npmInstall'
17:40:41.252 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger]
17:40:41.252 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :cogboard-webapp:npmInstall FAILED
17:40:41.266 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :cogboard-webapp:npmInstall' completed

#### Solution (optional)
1) add into wiki procedure how to build and launch after the firewall

### Acceptance Criteria
N/A

#### Additional context (optional)
N/A

**Comment by SebaM** [comment]
I've added few more flags as below, still checking but it fixed proxy issue:
malyska@sebaBox:~/dev/cogboard$ npm config set proxy http://135.245.X.X:8000
malyska@sebaBox:~/dev/cogboard$ npm config set https-proxy http://135.245.X.X:8000
malyska@sebaBox:~/dev/cogboard$ npm config set strict-ssl false

**Comment by SebaM** [comment]
The last step is proxy for docker since 17.07 and higher:
cat ~/.docker/config.json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://135.245.X.X:8000",
     "httpsProxy": "http://135.245.X.X:8000",
     "noProxy": "localhost,127.0.0.1,::1,localaddress,,*.YOUR.DOMAIN.com"
   }
 }
}

**Comment by szymon-owczarzak** [comment]
@SebaM - Thanks for this tip about setting proxies. We did not encounter this kind of issue as we don't use it as you do. When we setup CogBoard on our local PC's we are inside our private company network so there is no need to set up any proxies. With my current setup, I'm unable to test your solution but I will add a link to this issue in our [Tips & Tricks](https://github.com/Cognifide/cogboard/wiki#tips--tricks) wiki section.

Once again thanks for your help.

**Comment by SebaM** [comment]
No problem. This is a typical case "do once and forgot" ;-) .
My new deploy seems to be working at my side.
