### ISSUE TITLE
Checkbox vs API Ping

### ISSUE THREAD

**Issue by SebaM** [Cognifide/cogboard#251]
### Short Description
Team

I'm thinking about https://github.com/Cognifide/cogboard/wiki#Checkbox feature. Pls correct me if I'm wrong.
I need to have one front end place where I would like to present some status of my test/check. The Jenkins plugin is not addressing my needed since in one pipeline I perform plenty of this checks. So I figure out that I can use plugin Checkbox where I would present status: OK/NOT_OK/CHECKING. And the status will be changed via API during my pipeline work.
Thus I have two questions:
- have I understood well the goal for Checkbox feature
- is there any PING request in cogboard, just to confirm that my back end is working and ready to the status update

#### Solution (optional)
Set status OK if I needed.

### Acceptance Criteria
 - API Widget will respond OK on PING request

#### Additional context (optional)
N/A

**Comment by SebaM** [comment]
From that I check, it's working a little as I requested, see:
curl --noproxy 10.198.184.150  -d '{"id": "widget9","content": {"widgetStatus": "CHECKBOX_OK"}}' -H "Content-Type: application/json" -X POST http://10.198.184.150:8088/api/widget/contentUpdate
{"message":"Widget Content Updated","status":"success"}

The only case I had to do. To go on the start board, understand that {{Check}} is exactly the same as CheckBox (yes it's obvious, but w/o screen it was not ;-) ). Then go to edit of this plugin, find that widget id is not 17 as in doc example but for my installation is 9 and then change to request as upper.

**Comment by SebaM** [comment]
But still, some other status like IN_PROGRESS would be very nice to have.

**Comment by szymon-owczarzak** [comment]
Hi @SebaM , 

- Yes, thats correct - Checkbox widget is just presenting some kind of status out of 3 possible states: `CHECKBOX_OK`, `CHECKBOX_FAIL`, `CHECKBOX_UNKNOWN` and it can be set either by clicking or from API call.
- No, there is no PING call available

Please use `CHECKBOX_UNKNOWN` for IN_PROGRESS as we do not plan to add such state in the near future.
Also I've updated the Checkbox wiki section so widget `id` prop is more clear.

**Comment by szymon-owczarzak** [comment]
As no further question raised I'm closing this question. Feel free to reopen if needed.
