### ISSUE TITLE
Widget | Aggregated view of a Jira query (buckets)

### ISSUE THREAD

**Issue by andrzejkrej** [Cognifide/cogboard#258]
I would like to have a widget/tile that will show an aggregated view of a Jira query/filter in a form of a table.

 - [x] Admin can set a static header for the widget
 - [x] Admin can define a query sent to Jira
 - [x] Admin can define a list of "buckets"
 - [x] Admin can define a label and a "bucket query" for each bucket in the list

 - [x] User can see the header and a table of buckets
 - [x] Each bucket consists of a label and a number indicating number of items in the bucket

 - [ ] ~~Widget will send a single request to Jira~~
 - [ ] ~~Widget will split the response (flat list of tickets) into buckets, based on the "bucket queries"~~
 - [x] Widget will count the number of items in each bucket

Link to Jira API:
https://docs.atlassian.com/software/jira/docs/api/REST/8.5.3/#api/2/search-search

**Comment by andrzejkrej** [comment]
1. Widget sends a single request to Jira
	* query is authorable
2. Jira responds with a single array of items (tickets)
3. Widget splits the master array into subarrays (buckets) based on the "bucket queries"
	* bucket queries are authorable
4. Widget displays the list of buckets in the form of a table
	* each row in the table consists of the label and the number of items in the bucket
	* label for each bucket is authorable

**Comment by GulderBone** [comment]
https://github.com/Cognifide/cogboard/pull/261
