### ISSUE TITLE
Use `io.knotx.distribution` Gradle plugin

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/cogboard#43]
**Is your feature request related to a problem? Please describe.**

Knot.x Distribution Gradle plugin (`io.knotx.distribution`) allows to easily download Knot.x distribution (Knot.x Stack) with all dependencies and integrate them with custom modules.

**Describe the solution you'd like**
Use the `io.knotx.distribution` plugin instead of `gradle/distribution.gradle.kts`. Please check [Knot.x Starter Kit](https://github.com/Knotx/knotx-starter-kit) as a reference.

Please check lines:
```
tasks.register("prepareDocker") {
    dependsOn("cleanDistribution", "overwriteCustomFiles", "copyDockerfile")
}
```

**Additional context**
Improvements can be added with next versions of the plugin.

**Comment by szymon-owczarzak** [comment]
Thanks @tomaszmichalak, do You think if this is still valid if we have custom changes in `gradle/distribution.gradle.kts` ?

**Comment by szymon-owczarzak** [comment]
Implemented
