### ISSUE TITLE
Feature | Iframe dashboard

### ISSUE THREAD

**Issue by GrzegorzBednarski** [Cognifide/cogboard#82]
I want to have possibility to set whole dashboard as an one big Iframe (eg. grafana).

**AC**
- [ ] When adding new dashboard, Admin can choose additional Dashboard Type - Iframe Dashnboard
- [ ] Iframe Dashboard type should have field URL set as required (add front and backend validations)
- [ ] Dashboard with Iframe type shouldn't have possibility to add new widgets (still need possibility to save it)
- [ ] User should see full screen iframe as a selected dashboard (top menu bar with login/logout, dashboard picker and dashboard rotator should be still visible).

**Comment by szymon-owczarzak** [comment]
Done
